cc_library(
  name = "io-common",
  srcs = [],
  hdrs = glob([
    "err.h",
    "socket/socket.h",
    "poll/poller.h",
  ]),
  linkopts = ['-pthread'],
  visibility = ["//visibility:public"],
  linkstatic = 1,
)
